
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3307:3306"
###< doctrine/doctrine-bundle ###

  # Interface web pour administrer MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database
