version: '3.8'

services:
  # Base de données MySQL
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: concert_booking
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql

  # phpMyAdmin pour administrer MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  database_data: 