controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

easyadmin:
    resource: '../src/Controller/Admin/DashboardController.php'
    type: attribute
    prefix: /admin
