import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { ConcertDetailComponent } from './components/concert-detail/concert-detail.component';
import { ConcertListComponent } from './components/concert-list/concert-list.component';
import { SessionDetailComponent } from './components/session-detail/session-detail.component';
import { ArtistListComponent } from './components/artist-list/artist-list.component';
import { ArtistDetailComponent } from './components/artist-detail/artist-detail.component';
import { HallListComponent } from './components/hall-list/hall-list.component';
import { HallDetailComponent } from './components/hall-detail/hall-detail.component';
import { CategoryListComponent } from './components/category-list/category-list.component';
import { CategoryDetailComponent } from './components/category-detail/category-detail.component';
import { SubscriptionFormComponent } from './components/subscription-form/subscription-form.component';
import { LoginComponent } from './components/login/login.component';
import { authGuard } from './guards/auth.guard';
import { CartComponent } from './components/cart/cart.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'concert', component: ConcertListComponent },
  { path: 'concert/:id', component: ConcertDetailComponent },
  { path: 'concert/:id/sessions', component: SessionDetailComponent },
  { path: 'session/:sessionId', component: SessionDetailComponent },
  { path: 'hall', component: HallListComponent },
  { path: 'hall/:id', component: HallDetailComponent },
  { path: 'artist', component: ArtistListComponent },
  { path: 'artist/:id', component: ArtistDetailComponent },
  { path: 'category', component: CategoryListComponent },
  { path: 'category/:id', component: CategoryDetailComponent },
  { path: 'subscription-form', component: SubscriptionFormComponent },
  { path: 'login', component: LoginComponent },
  { path: 'cart', component: CartComponent },
  { path: '**', redirectTo: '' }
];
